const defaultConfig = {
  URL_GET_PROFILE: "/api/employee/getprofile",
  URL_GET_ALL_SDRS: "/api/Elb/GetAllEsfrRecords",
  URL_GET_SDR_ESFR_RECORD_DETAILS: "/api/Elb/GetSdrEsfrRecordDetails",
  URL_GET_APPROVED_SDR: "/api/Elb/GetApprovedSdr",
  // URL_ESFR_APPROVE: "/api/Elb/UpdateEsfrRecordStatus",
  URL_LOGPAGE_SEARCH: "/Home/LogPageSearch",
  URL_GET_SFR_MASTER_DATA: "/api/Elb/GetSfrMasterData",
  // URL_ADD_SDR: "/api/Elb/UpdateLogPageWithOilandMaterialLabor",
  URL_CREATE_SDR: "/api/Elb/CreateSDR",
  URL_CREATE_SFR: "/api/Elb/CreateSFR",
  URL_VIEW_LOGPAGE: "/api/Elb/ViewLogPage",
  URL_DOES_SDR_EXISTS: "/api/Elb/DoesSdrExists",
  URL_EXTRACT_SDR_RECORDS: "/api/Elb/ExtractSdrRecords",
  URL_UPDATE_SNAPSHOT_SDR_EXTRACTION_STATUS: "/api/Elb/UpdateSnapshotSdrExtractionStatus",
  URL_INSERT_SNAPSHOT_SDR_FILENAME: "/api/Elb/InsertSnapshotSdrFilename",
  URL_UPSERT_SDR_SNAPSHOT: "/api/Elb/UpsertSdrSnapshot",
  URL_UPSERT_SFR_SNAPSHOT: "/api/Elb/UpsertSfrSnapshot",
  URL_GET_ESFR_REPORT: "/api/Elb/GetEsfrReport",
  URL_GET_CPCP_REPORT: "/api/Elb/GetCpcpReport",
  URL_GET_PARTS_REPORT: "/api/Elb/GetPartsDiscrepancyReport",
  URL_GET_CTN: "/api/Elb/GetCtn",
  URL_GET_SID: "/api/Elb/GetSid",
  URL_GET_LOCATION_STA_DATA: "/api/Elb/GetLocationStaData",
};

export default defaultConfig;
